# Generated by Django 6.0.6 on 2026-06-07 08:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                            ("free_trial", "Free Trial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("max_uses_per_user", models.PositiveIntegerField(default=1)),
                ("current_uses", models.PositiveIntegerField(default=0)),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("new_users_only", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "coupons",
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "coupon_usages",
            },
        ),
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=10)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("bitcoin", "Bitcoin"),
                            ("ethereum", "Ethereum"),
                            ("tron", "Tron"),
                            ("bsc", "Binance Smart Chain"),
                            ("polygon", "Polygon"),
                        ],
                        max_length=20,
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                (
                    "private_key",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="crypto_icons/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("auto_convert_to_usd", models.BooleanField(default=True)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("last_rate_update", models.DateTimeField(blank=True, null=True)),
                ("required_confirmations", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cryptocurrencies",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("order_number", models.CharField(max_length=20, unique=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("new_subscription", "New Subscription"),
                            ("renewal", "Renewal"),
                            ("upgrade", "Upgrade"),
                            ("gift", "Gift Purchase"),
                        ],
                        default="new_subscription",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("paid", "Paid"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("coupon_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "coupon_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "selected_payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card_transfer", "Card Transfer"),
                            ("online_gateway", "Online Gateway"),
                            ("cryptocurrency", "Cryptocurrency"),
                            ("telegram_stars", "Telegram Stars"),
                            ("wallet", "Wallet"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("awaiting_confirmation", "Awaiting Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "gateway_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                (
                    "receipt_image",
                    models.ImageField(blank=True, null=True, upload_to="receipts/"),
                ),
                (
                    "receipt_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("card_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cardholder_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "crypto_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "crypto_amount",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "crypto_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "crypto_txid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stars_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "telegram_payment_charge_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("card_number", models.CharField(max_length=20)),
                ("cardholder_name", models.CharField(max_length=100)),
                ("card_type", models.CharField(blank=True, max_length=50, null=True)),
                ("card_color", models.CharField(default="#007bff", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("total_payments", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_cards",
                "ordering": ["display_order", "bank_name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gateway_type",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("razorpay", "Razorpay"),
                            ("zarinpal", "ZarinPal"),
                            ("idpay", "IDPay"),
                            ("custom", "Custom Gateway"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(max_length=500)),
                ("secret_key", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "merchant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_sandbox", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("supported_currencies", models.JSONField(blank=True, default=list)),
                (
                    "transaction_fee_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "fixed_transaction_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("callback_url", models.URLField(blank=True, null=True)),
                ("webhook_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_gateways",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("is_frozen", models.BooleanField(default=False)),
                (
                    "daily_spending_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "monthly_spending_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("bonus", "Bonus"),
                            ("referral_reward", "Referral Reward"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "wallet_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
