# Generated by Django 6.0.6 on 2026-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_file",
            field=models.TextField(blank=True, null=True),
        ),
    ]
