# Generated by Django 6.0.6 on 2026-09-26 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
        ("orders", "0004_payment_wallet_alter_payment_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "confirmed")),
                fields=("order",),
                name="uniq_confirmed_payment_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                fields=("user", "brand"), name="uniq_wallet_per_user_brand"
            ),
        ),
    ]
