# Generated by Django 6.0.6 on 2026-09-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_wallet_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("new_subscription", "New Subscription"),
                    ("renewal", "Renewal"),
                    ("upgrade", "Upgrade"),
                    ("gift", "Gift Purchase"),
                    ("reward_redemption", "Reward Redemption"),
                ],
                default="new_subscription",
                max_length=20,
            ),
        ),
    ]
