# Generated by Django 6.0.6 on 2026-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_order_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="amount",
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="balance_after",
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="balance_before",
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
