# Generated by Django 6.0.6 on 2026-09-26 08:57

from django.db import migrations, models


def copy_current_plan_cost(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.select_related("plan").iterator(chunk_size=500):
        order.upstream_cost_snapshot = order.plan.upstream_cost
        order.save(update_fields=["upstream_cost_snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_wallet_balance_alter_wallettransaction_amount_and_more"),
        ("subscriptions", "0006_subscription_provisioning_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="upstream_cost_snapshot",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=15
            ),
        ),
        migrations.RunPython(copy_current_plan_cost, migrations.RunPython.noop),
    ]
