# Generated by Django 6.0.6 on 2026-09-26 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_upstream_cost_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponusage",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_usages",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="telegram_payment_charge_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
