# Generated by Django 6.0.6 on 2026-10-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_wallet_challenge_frozen_balance"),
        ("referrals", "0012_alter_gamificationnotification_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gift_reward_challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gift_orders",
                to="referrals.userchallenge",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_reward_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_telegram_username",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
