# Generated by Django 6.0.6 on 2026-06-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("referral", "Referral Achievement"),
                            ("purchase", "Purchase Achievement"),
                            ("loyalty", "Loyalty Achievement"),
                            ("social", "Social Achievement"),
                            ("milestone", "Milestone Achievement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="achievements/"),
                ),
                ("color", models.CharField(default="#ffd700", max_length=7)),
                ("requirements", models.JSONField(blank=True, default=dict)),
                ("reward_points", models.PositiveIntegerField(default=0)),
                (
                    "reward_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_repeatable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "achievements",
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(default="Loyalty Program", max_length=100)),
                (
                    "points_per_dollar",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("points_per_referral", models.PositiveIntegerField(default=100)),
                ("min_redemption_points", models.PositiveIntegerField(default=100)),
                (
                    "point_value_usd",
                    models.DecimalField(decimal_places=4, default=0.01, max_digits=5),
                ),
                (
                    "points_expire_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_program",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "loyalty_programs",
            },
        ),
        migrations.CreateModel(
            name="MarketingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("banner", "Banner"),
                            ("text_template", "Text Template"),
                            ("video", "Video"),
                            ("social_post", "Social Media Post"),
                            ("email_template", "Email Template"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="marketing/"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="marketing/videos/"
                    ),
                ),
                ("target_audience", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_materials",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "marketing_materials",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("custom_code", models.CharField(blank=True, max_length=50, null=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("conversion_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "campaign_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_links",
                        to="brands.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "referral_links",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("converted", "Converted"),
                            ("rewarded", "Rewarded"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referrer_reward_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "referee_reward_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("rewarded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="brands.brand",
                    ),
                ),
                (
                    "conversion_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="referrals.referrallink",
                    ),
                ),
            ],
            options={
                "db_table": "referrals",
            },
        ),
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(default="Referral Program", max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "referrer_reward_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of Purchase"),
                            ("fixed_amount", "Fixed Amount"),
                            ("points", "Reward Points"),
                            ("free_days", "Free Days"),
                            ("custom", "Custom Reward"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "referrer_reward_value",
                    models.DecimalField(decimal_places=2, default=10, max_digits=15),
                ),
                (
                    "referrer_max_reward",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "referee_reward_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of Purchase"),
                            ("fixed_amount", "Fixed Amount"),
                            ("points", "Reward Points"),
                            ("free_days", "Free Days"),
                            ("custom", "Custom Reward"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "referee_reward_value",
                    models.DecimalField(decimal_places=2, default=5, max_digits=15),
                ),
                (
                    "referee_max_reward",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("require_purchase", models.BooleanField(default=True)),
                (
                    "minimum_purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("enable_level_rewards", models.BooleanField(default=False)),
                ("conversion_window_days", models.PositiveIntegerField(default=30)),
                ("max_referrals_per_day", models.PositiveIntegerField(default=10)),
                ("max_referrals_per_month", models.PositiveIntegerField(default=100)),
                ("same_ip_limit", models.PositiveIntegerField(default=3)),
                ("require_phone_verification", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_program",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "referral_programs",
            },
        ),
        migrations.CreateModel(
            name="ReferralLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("min_referrals", models.PositiveIntegerField()),
                (
                    "min_conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "reward_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "bonus_reward",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="referrals.referralprogram",
                    ),
                ),
            ],
            options={
                "db_table": "referral_levels",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reward_type", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_rewards",
                        to="brands.brand",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="referrals.referral",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "referral_rewards",
            },
        ),
        migrations.CreateModel(
            name="ReferralStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("registrations", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                (
                    "total_rewards",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_stats",
                        to="brands.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "referral_stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reward_claimed", models.BooleanField(default=False)),
                ("reward_claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="referrals.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_achievements",
            },
        ),
        migrations.AddIndex(
            model_name="referrallink",
            index=models.Index(fields=["code"], name="referral_li_code_ecd792_idx"),
        ),
        migrations.AddIndex(
            model_name="referrallink",
            index=models.Index(
                fields=["user", "brand"], name="referral_li_user_id_531b5c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referrallink",
            unique_together={("user", "brand")},
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referrer", "status"], name="referrals_referre_cefb5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referee", "brand"], name="referrals_referee_458a1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["status", "created_at"], name="referrals_status_918a2d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referral",
            unique_together={("referrer", "referee", "brand")},
        ),
        migrations.AlterUniqueTogether(
            name="referrallevel",
            unique_together={("program", "level")},
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["user", "status"], name="referral_re_user_id_d7bd23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["brand", "created_at"], name="referral_re_brand_i_ff079d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referralstats",
            unique_together={("user", "brand", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("user", "achievement")},
        ),
    ]
