# Generated by Django 6.0.6 on 2026-09-26 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
        ("orders", "0005_alter_wallet_unique_together_and_more"),
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referral",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="referral",
            constraint=models.UniqueConstraint(
                fields=("referee", "brand"), name="uniq_referral_attribution_per_brand"
            ),
        ),
    ]
