# Generated by Django 6.0.6 on 2026-09-26 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
        ("orders", "0005_alter_wallet_unique_together_and_more"),
        ("referrals", "0002_alter_referral_unique_together_and_more"),
        ("subscriptions", "0005_subscriptionplan_upstream_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liquid_points",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "lifetime_points",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "lifetime_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("next_box_cycle", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reward_accounts",
            },
        ),
        migrations.CreateModel(
            name="RewardBoxCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("capacity", models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                "db_table": "reward_box_capacities",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="RewardPointBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle", models.PositiveIntegerField(default=1)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("capacity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "filled",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "point_value_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("complete", "Complete"),
                            ("converted", "Converted"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reward_point_boxes",
                "ordering": ["cycle", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="RewardPointLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("earned", "Earned"),
                            ("box_completed", "Box Completed"),
                            ("service_rebase", "Service Rebase"),
                            ("converted_to_wallet", "Converted to Wallet"),
                        ],
                        max_length=24,
                    ),
                ),
                ("points_delta", models.DecimalField(decimal_places=8, max_digits=20)),
                ("value_delta", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "point_value_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reward_point_ledger",
            },
        ),
        migrations.CreateModel(
            name="RewardService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_points",
                    models.DecimalField(decimal_places=8, default=10, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reward_services",
            },
        ),
        migrations.AddField(
            model_name="referrallevel",
            name="badge",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="referrallevel",
            name="min_lifetime_points",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_rewards",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referee_reward_amount",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referrer_reward_amount",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="referralreward",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AddConstraint(
            model_name="referralreward",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order__isnull", False)),
                fields=("order",),
                name="uniq_referral_reward_per_order",
            ),
        ),
        migrations.AddField(
            model_name="rewardaccount",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_accounts",
                to="brands.brand",
            ),
        ),
        migrations.AddField(
            model_name="rewardaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rewardpointbox",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxes",
                to="referrals.rewardaccount",
            ),
        ),
        migrations.AddField(
            model_name="rewardpointledger",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="referrals.rewardaccount",
            ),
        ),
        migrations.AddField(
            model_name="rewardpointledger",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="rewardpointledger",
            name="referral_reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="referrals.referralreward",
            ),
        ),
        migrations.AddField(
            model_name="rewardservice",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_services",
                to="brands.brand",
            ),
        ),
        migrations.AddField(
            model_name="rewardservice",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reward_service_configs",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="rewardpointledger",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="referrals.rewardservice",
            ),
        ),
        migrations.AddField(
            model_name="rewardpointbox",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="point_boxes",
                to="referrals.rewardservice",
            ),
        ),
        migrations.AddField(
            model_name="rewardboxcapacity",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_capacities",
                to="referrals.rewardservice",
            ),
        ),
        migrations.AddField(
            model_name="rewardaccount",
            name="reference_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="referrals.rewardservice",
            ),
        ),
        migrations.AddField(
            model_name="referralprogram",
            name="lifetime_reference_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lifetime_programs",
                to="referrals.rewardservice",
            ),
        ),
        migrations.AddField(
            model_name="referralprogram",
            name="reference_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_programs",
                to="referrals.rewardservice",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardservice",
            constraint=models.UniqueConstraint(
                fields=("brand", "plan"), name="uniq_reward_service_plan"
            ),
        ),
        migrations.AddIndex(
            model_name="rewardpointledger",
            index=models.Index(
                fields=["account", "created_at"], name="reward_poin_account_9e4ff0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardpointbox",
            constraint=models.UniqueConstraint(
                fields=("account", "service", "cycle", "sequence"),
                name="uniq_reward_point_box_cycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardpointbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gt", 0)),
                name="reward_point_box_capacity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardpointbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("filled__gte", 0)),
                name="reward_point_box_filled_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardboxcapacity",
            constraint=models.UniqueConstraint(
                fields=("service", "sequence"), name="uniq_reward_box_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardboxcapacity",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gt", 0)),
                name="reward_box_capacity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "brand"), name="uniq_reward_account_user_brand"
            ),
        ),
    ]
