# Generated by Django 6.0.6 on 2026-09-26 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_order_type"),
        ("referrals", "0003_rewardaccount_rewardboxcapacity_rewardpointbox_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardaccount",
            name="redemption_nonce",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="rewardpointledger",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("earned", "Earned"),
                    ("box_completed", "Box Completed"),
                    ("service_rebase", "Service Rebase"),
                    ("converted_to_wallet", "Converted to Wallet"),
                    ("redeemed", "Redeemed"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_spent", models.DecimalField(decimal_places=8, max_digits=20)),
                ("idempotency_key", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="referrals.rewardaccount",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward_redemption",
                        to="orders.order",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="referrals.rewardservice",
                    ),
                ),
            ],
            options={
                "db_table": "reward_redemptions",
            },
        ),
    ]
