# Generated by Django 6.0.6 on 2026-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0004_rewardaccount_redemption_nonce_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardpointledger",
            name="value_delta",
            field=models.DecimalField(decimal_places=10, max_digits=26),
        ),
    ]
