# Generated by Django 6.0.6 on 2026-09-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0005_alter_rewardpointledger_value_delta"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralprogram",
            name="lifetime_point_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="rewardservice",
            name="point_value_snapshot",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
