# Generated by Django 6.0.6 on 2026-09-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0006_referralprogram_lifetime_point_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardpointbox",
            name="spent_points",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddConstraint(
            model_name="rewardpointbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("filled__lte", models.F("capacity"))),
                name="reward_point_box_filled_within_capacity",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardpointbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("spent_points__gte", 0)),
                name="reward_point_box_spent_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardpointbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("spent_points__lte", models.F("filled"))),
                name="reward_point_box_spent_within_filled",
            ),
        ),
    ]
