# Generated by Django 6.0.6 on 2026-09-26 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
        ("referrals", "0007_rewardpointbox_spent_points_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userachievement",
            name="claim_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="requirements",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Thresholds: referrals, conversions, purchases, lifetime_points, total_spent, wallet_deposits. Example: {"referrals": 5}.',
            ),
        ),
        migrations.AlterField(
            model_name="rewardpointledger",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("earned", "Earned"),
                    ("box_completed", "Box Completed"),
                    ("service_rebase", "Service Rebase"),
                    ("converted_to_wallet", "Converted to Wallet"),
                    ("redeemed", "Redeemed"),
                    ("achievement_bonus", "Achievement Bonus"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ReferralClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_visits",
                        to="brands.brand",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="referrals.referrallink",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "referral_clicks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("link", "visitor"), name="uniq_referral_visit_per_user"
                    )
                ],
            },
        ),
    ]
