# Generated by Django 6.0.6 on 2026-10-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0010_challenge_join_window_policy"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gamificationnotification",
            new_name="gamificatio_brand_i_4d4980_idx",
            old_name="gamificatio_brand_i_b14651_idx",
        ),
        migrations.RenameIndex(
            model_name="userchallenge",
            new_name="user_challe_brand_i_412ed0_idx",
            old_name="user_challe_brand_i_95f9d1_idx",
        ),
        migrations.RenameIndex(
            model_name="userchallenge",
            new_name="user_challe_user_id_ecb192_idx",
            old_name="user_challe_user_id_c02c03_idx",
        ),
    ]
