# Generated by Django 6.0.6 on 2026-10-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "referrals",
            "0011_rename_gamificatio_brand_i_b14651_idx_gamificatio_brand_i_4d4980_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamificationnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("survey", "Survey"),
                    ("referral_intro", "Referral intro"),
                    ("challenge_offer", "Challenge offer"),
                    ("challenge_reminder", "Challenge reminder"),
                    ("expiry_5d", "Subscription expiry 5d"),
                    ("referral_reward", "Referral reward"),
                    ("profile_completion", "Profile completion reminder"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="referralreward",
            name="referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rewards",
                to="referrals.referral",
            ),
        ),
    ]
