# Generated by Django 6.0.6 on 2026-06-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_brands",
            field=models.ManyToManyField(
                blank=True, related_name="admin_users", to="brands.brand"
            ),
        ),
    ]
