# Generated by Django 6.0.6 on 2026-10-09 17:55

from django.db import migrations, models


def preserve_devices(apps, schema_editor):
    profiles = apps.get_model("accounts", "UserProfile")
    for profile in (
        profiles.objects.using(schema_editor.connection.alias)
        .exclude(device_type__isnull=True)
        .exclude(device_type="")
        .iterator()
    ):
        profile.devices = [profile.device_type]
        profile.save(using=schema_editor.connection.alias, update_fields=["devices"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_userprofile_device_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="devices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="living_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_reward_granted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="work_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(preserve_devices, migrations.RunPython.noop),
    ]
