# Generated by Django 6.0.6 on 2026-06-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("domain", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="brands/logos/"),
                ),
                ("primary_color", models.CharField(default="#007bff", max_length=7)),
                ("secondary_color", models.CharField(default="#6c757d", max_length=7)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "support_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("bot_token", models.CharField(max_length=255, unique=True)),
                (
                    "bot_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("webhook_url", models.URLField(blank=True, null=True)),
                (
                    "telegram_channel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "telegram_group",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending Approval"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "brands",
                "indexes": [
                    models.Index(fields=["status"], name="brands_status_28bd17_idx"),
                    models.Index(fields=["slug"], name="brands_slug_6a4b1c_idx"),
                    models.Index(
                        fields=["created_at"], name="brands_created_5b9afc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrandApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("permissions", models.JSONField(default=list)),
                ("rate_limit_per_hour", models.PositiveIntegerField(default=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_api_keys",
            },
        ),
        migrations.CreateModel(
            name="BrandConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(default="Welcome to our VPN service!"),
                ),
                ("help_message", models.TextField(blank=True, null=True)),
                ("referral_system_enabled", models.BooleanField(default=True)),
                ("wallet_system_enabled", models.BooleanField(default=True)),
                ("support_system_enabled", models.BooleanField(default=True)),
                ("analytics_enabled", models.BooleanField(default=True)),
                ("max_subscriptions_per_user", models.PositiveIntegerField(default=10)),
                ("max_referrals_per_day", models.PositiveIntegerField(default=100)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_configurations",
            },
        ),
        migrations.CreateModel(
            name="BrandPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("card_transfer", "Card Transfer"),
                            ("online_gateway", "Online Gateway"),
                            ("cryptocurrency", "Cryptocurrency"),
                            ("telegram_stars", "Telegram Stars"),
                            ("wallet", "Wallet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="payment_icons/"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_payment_methods",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BrandTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("rounded", "Rounded"),
                            ("square", "Square"),
                            ("pill", "Pill"),
                        ],
                        default="rounded",
                        max_length=20,
                    ),
                ),
                (
                    "menu_style",
                    models.CharField(
                        choices=[
                            ("grid", "Grid"),
                            ("list", "List"),
                            ("carousel", "Carousel"),
                        ],
                        default="grid",
                        max_length=20,
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="brands/backgrounds/"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="brands/banners/"
                    ),
                ),
                ("font_family", models.CharField(default="Arial", max_length=50)),
                ("custom_css", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_themes",
            },
        ),
        migrations.CreateModel(
            name="BrandWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("events", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("secret", models.CharField(blank=True, max_length=255, null=True)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("retry_delay", models.PositiveIntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_webhooks",
            },
        ),
        migrations.CreateModel(
            name="BrandAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("total_users", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("orders_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("new_referrals", models.PositiveIntegerField(default=0)),
                (
                    "referral_conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("support_tickets", models.PositiveIntegerField(default=0)),
                ("resolved_tickets", models.PositiveIntegerField(default=0)),
                ("avg_response_time", models.DurationField(blank=True, null=True)),
                (
                    "total_traffic_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("peak_concurrent_users", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_analytics",
                "ordering": ["-date"],
                "unique_together": {("brand", "date")},
            },
        ),
        migrations.CreateModel(
            name="BrandSocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("is_primary", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_social_media",
                "unique_together": {("brand", "platform", "username")},
            },
        ),
    ]
