# Generated by Django 6.0.6 on 2026-10-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="invite_only_registration",
            field=models.BooleanField(
                default=False,
                help_text="با فعال شدن این گزینه، کاربران جدید فقط با لینک دعوت فعال همین برند وارد می\u200cشوند. کاربران موجود محدودیتی ندارند.",
                verbose_name="ورود کاربران جدید فقط با لینک دعوت",
            ),
        ),
    ]
