# Generated by Django 6.0.6 on 2026-06-07 08:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        ("orders", "0001_initial"),
        ("vpn_providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("vpn_user_email", models.CharField(max_length=255)),
                ("is_gift", models.BooleanField(default=False)),
                ("gift_message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending Activation"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "traffic_used_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "traffic_limit_gb",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("subscription_url", models.TextField(blank=True, null=True)),
                ("connection_configs", models.JSONField(blank=True, default=dict)),
                ("qr_codes", models.JSONField(blank=True, default=list)),
                (
                    "connectix_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "connectix_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("auto_renewal_enabled", models.BooleanField(default=False)),
                ("expiry_notification_sent", models.BooleanField(default=False)),
                ("traffic_warning_sent", models.BooleanField(default=False)),
                ("last_connection", models.DateTimeField(blank=True, null=True)),
                ("total_connections", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="brands.brand",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="orders.order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vpn_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="vpn_providers.vpnprovider",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vmess_config", models.JSONField(blank=True, null=True)),
                ("vless_config", models.JSONField(blank=True, null=True)),
                ("trojan_config", models.JSONField(blank=True, null=True)),
                ("shadowsocks_config", models.JSONField(blank=True, null=True)),
                ("wireguard_config", models.JSONField(blank=True, null=True)),
                ("subscription_url", models.TextField(blank=True, null=True)),
                ("qr_code_data", models.JSONField(blank=True, default=list)),
                ("server_info", models.JSONField(blank=True, default=dict)),
                ("clash_config", models.TextField(blank=True, null=True)),
                ("v2ray_config", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_configs",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("unlimited", "Unlimited"),
                            ("traffic_based", "Traffic Based"),
                            ("time_based", "Time Based"),
                            ("hybrid", "Hybrid (Traffic + Time)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("duration_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "traffic_limit_gb",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("max_users", models.PositiveIntegerField(default=1)),
                ("features", models.JSONField(blank=True, default=list)),
                ("allowed_protocols", models.JSONField(blank=True, default=list)),
                ("server_locations", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("offer_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_plans",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["display_order", "price"],
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionRenewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "renewal_type",
                    models.CharField(
                        choices=[
                            ("renewal", "Renewal"),
                            ("upgrade", "Upgrade"),
                            ("downgrade", "Downgrade"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_expires_at", models.DateTimeField()),
                ("new_expires_at", models.DateTimeField()),
                ("traffic_added_gb", models.PositiveIntegerField(default=0)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "new_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_renewals",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "old_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_renewals",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="orders.order",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_renewals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscription_transfers",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("upload_bytes", models.BigIntegerField(default=0)),
                ("download_bytes", models.BigIntegerField(default=0)),
                ("connection_count", models.PositiveIntegerField(default=0)),
                ("online_duration_minutes", models.PositiveIntegerField(default=0)),
                ("peak_concurrent_connections", models.PositiveIntegerField(default=0)),
                ("servers_used", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_usage",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("expiry_warning", "Expiry Warning"),
                            ("expired", "Expired"),
                            ("traffic_warning", "Traffic Warning"),
                            ("traffic_exhausted", "Traffic Exhausted"),
                            ("renewal_reminder", "Renewal Reminder"),
                            ("activated", "Activated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_method",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_notifications",
                "indexes": [
                    models.Index(
                        fields=["scheduled_for", "is_sent"],
                        name="subscriptio_schedul_0d17b1_idx",
                    ),
                    models.Index(
                        fields=["subscription", "notification_type"],
                        name="subscriptio_subscri_741442_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["brand", "status"], name="subscriptio_brand_i_a55573_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "status"], name="subscriptio_user_id_8d58fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["expires_at"], name="subscriptio_expires_af5d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["vpn_provider", "vpn_user_email"],
                name="subscriptio_vpn_pro_63ac6d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscriptionusage",
            unique_together={("subscription", "date")},
        ),
    ]
