# Generated by Django 6.0.6 on 2026-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="vpn_user_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
