# Generated by Django 6.0.6 on 2026-09-26 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
        ("orders", "0004_payment_wallet_alter_payment_order"),
        ("subscriptions", "0002_alter_subscription_vpn_user_email"),
        ("vpn_providers", "0004_vpnprovider_last_sync"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderRemoteSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_id", models.CharField(blank=True, max_length=128, null=True)),
                ("username", models.CharField(blank=True, max_length=100)),
                ("subscription_url", models.TextField(blank=True)),
                ("remote_status", models.CharField(blank=True, max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("error", "Error"),
                        ],
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "provider_remote_subscriptions",
            },
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="upstream_group_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="upstream_group_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="upstream_plan_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="upstream_plan_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="vpn_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_plans",
                to="vpn_providers.vpnprovider",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("order",), name="uniq_subscription_per_order"
            ),
        ),
        migrations.AddField(
            model_name="providerremotesubscription",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="remote_subscriptions",
                to="vpn_providers.vpnprovider",
            ),
        ),
        migrations.AddField(
            model_name="providerremotesubscription",
            name="subscription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remote_account",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="providerremotesubscription",
            index=models.Index(
                fields=["provider", "state"], name="provider_re_provide_d17cbe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerremotesubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("remote_id__isnull", False)),
                fields=("provider", "remote_id"),
                name="uniq_provider_remote_subscription_id",
            ),
        ),
    ]
