# Generated by Django 6.0.6 on 2026-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_providerremotesubscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="connectix_password",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="upstream_count_of_devices",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
