# Generated by Django 6.0.6 on 2026-09-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_remove_subscription_connectix_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="upstream_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
