# Generated by Django 6.0.6 on 2026-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_subscriptionplan_upstream_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="provisioning_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
