# Generated by Django 6.0.6 on 2026-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_subscription_provisioning_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="provisioning_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
