# Generated by Django 6.0.6 on 2026-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_subscription_provisioning_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="provisioning_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="provisioning_error_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="subscription",
            name="provisioning_retryable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="provisioning_state",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("retryable_error", "Retryable error"),
                    ("needs_review", "Needs review"),
                    ("unsupported", "Unsupported"),
                    ("active", "Active"),
                ],
                default="queued",
                max_length=24,
            ),
        ),
    ]
