# Generated by Django 6.0.6 on 2026-09-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscription_provisioning_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="traffic_limit_gb",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="traffic_limit_gb",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
