# Generated by Django 6.0.6 on 2026-10-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_subscriptionclaim"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subscriptionclaim",
            new_name="subscriptio_brand_i_e6a388_idx",
            old_name="subscriptio_brand_i_22de41_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionclaim",
            new_name="subscriptio_user_id_a326eb_idx",
            old_name="subscriptio_user_id_e33833_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_brand_i_22de41_idx",
            old_name="subscriptio_brand_i_a55573_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_user_id_e33833_idx",
            old_name="subscriptio_user_id_8d58fd_idx",
        ),
    ]
