# Generated by Django 6.0.6 on 2026-06-07 08:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        ("orders", "0001_initial"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("response_time_hours", models.PositiveIntegerField(default=24)),
                ("resolution_time_hours", models.PositiveIntegerField(default=72)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auto_assign_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_categories",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "support_categories",
                "ordering": ["display_order", "name"],
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer Message"),
                            ("agent", "Agent Reply"),
                            ("system", "System Message"),
                            ("internal", "Internal Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("is_public", models.BooleanField(default=True)),
                ("is_read_by_customer", models.BooleanField(default=False)),
                ("is_read_by_agent", models.BooleanField(default=False)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "support_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="support_attachments/")),
                ("file_size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("is_scanned", models.BooleanField(default=False)),
                ("scan_result", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_attachments",
                        to="support.supportmessage",
                    ),
                ),
            ],
            options={
                "db_table": "support_attachments",
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("ticket_number", models.CharField(max_length=20, unique=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("pending_customer", "Pending Customer Response"),
                            ("pending_internal", "Pending Internal Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram Bot"),
                            ("web", "Web Panel"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("api", "API"),
                        ],
                        default="telegram",
                        max_length=20,
                    ),
                ),
                ("sla_response_due", models.DateTimeField(blank=True, null=True)),
                ("sla_resolution_due", models.DateTimeField(blank=True, null=True)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("response_sla_breached", models.BooleanField(default=False)),
                ("resolution_sla_breached", models.BooleanField(default=False)),
                (
                    "customer_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("customer_feedback", models.TextField(blank=True, null=True)),
                ("feedback_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_escalated", models.BooleanField(default=False)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("escalation_reason", models.TextField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to="brands.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="support.supportcategory",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalated_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "related_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "support_tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="support.supportticket",
            ),
        ),
        migrations.CreateModel(
            name="SupportEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escalation_type",
                    models.CharField(
                        choices=[
                            ("sla_breach", "SLA Breach"),
                            ("customer_request", "Customer Request"),
                            ("agent_escalation", "Agent Escalation"),
                            ("supervisor_review", "Supervisor Review"),
                            ("technical_complexity", "Technical Complexity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("resolution", models.TextField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "escalated_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "db_table": "support_escalations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportAutomation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("ticket_created", "Ticket Created"),
                            ("ticket_updated", "Ticket Updated"),
                            ("message_received", "Message Received"),
                            ("sla_warning", "SLA Warning"),
                            ("customer_rating", "Customer Rating"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trigger_conditions", models.JSONField(blank=True, default=dict)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("auto_assign", "Auto Assign"),
                            ("send_template", "Send Template"),
                            ("escalate", "Escalate Ticket"),
                            ("add_tag", "Add Tag"),
                            ("change_priority", "Change Priority"),
                            ("notify_manager", "Notify Manager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("execution_count", models.PositiveIntegerField(default=0)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_automations",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "support_automations",
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="SupportKnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("slug", models.SlugField(max_length=255)),
                ("meta_description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("helpful_votes", models.PositiveIntegerField(default=0)),
                ("not_helpful_votes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_articles",
                        to="brands.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="support.supportcategory",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "support_knowledge_base",
                "indexes": [
                    models.Index(
                        fields=["brand", "status"],
                        name="support_kno_brand_i_126f28_idx",
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="support_kno_categor_1d0c57_idx",
                    ),
                ],
                "unique_together": {("brand", "slug")},
            },
        ),
        migrations.CreateModel(
            name="SupportMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("tickets_created", models.PositiveIntegerField(default=0)),
                ("tickets_resolved", models.PositiveIntegerField(default=0)),
                ("tickets_closed", models.PositiveIntegerField(default=0)),
                (
                    "avg_first_response_time_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                ("avg_resolution_time_minutes", models.PositiveIntegerField(default=0)),
                (
                    "sla_response_compliance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sla_resolution_compliance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_customer_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                ("active_tickets", models.PositiveIntegerField(default=0)),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_metrics",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "support_metrics",
                "ordering": ["-date"],
                "unique_together": {("brand", "agent", "date")},
            },
        ),
        migrations.CreateModel(
            name="SupportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("quick_response", "Quick Response"),
                            ("resolution", "Resolution Template"),
                            ("escalation", "Escalation Template"),
                            ("closing", "Closing Template"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("content_template", models.TextField()),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_templates",
                        to="brands.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="support.supportcategory",
                    ),
                ),
            ],
            options={
                "db_table": "support_templates",
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["brand", "status"], name="support_tic_brand_i_b0e4e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["customer", "status"], name="support_tic_custome_6b614c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["assigned_to", "status"], name="support_tic_assigne_9415d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["ticket_number"], name="support_tic_ticket__441438_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["sla_response_due"], name="support_tic_sla_res_052d4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["sla_resolution_due"], name="support_tic_sla_res_82bc53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportmessage",
            index=models.Index(
                fields=["ticket", "created_at"], name="support_mes_ticket__779ccd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="support_mes_sender__c1d4b2_idx"
            ),
        ),
    ]
