# Generated by Django 6.0.6 on 2026-10-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0002_usefulcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("android_samsung", "اندروید سامسونگ"),
                    ("android_other", "شیائومی و سایر"),
                    ("iphone", "آیفون"),
                    ("windows", "ویندوز"),
                    ("macos", "مکینتاش"),
                    ("linux", "لینوکس"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="usefulcontent",
            name="app_family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("connectix", "Connectix"),
                    ("v2rayng", "v2rayNG"),
                    ("happ", "Happ"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="usefulcontent",
            name="installer_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="usefulcontent",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("iphone", "iPhone"),
                    ("android", "Android"),
                    ("windows", "Windows"),
                    ("macos", "macOS"),
                    ("linux", "Linux"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="usefulcontent",
            name="telegram_file_id",
            field=models.CharField(
                blank=True,
                help_text="Telegram file_id for installers already uploaded to this bot, including files over 50 MB.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="usefulcontent",
            name="variant",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="usefulcontent",
            name="category",
            field=models.CharField(
                choices=[
                    ("downloads", "App files and download links"),
                    ("install", "Install and import subscription"),
                    ("app_usage", "Application usage guide"),
                    ("faq", "Frequently asked questions"),
                    ("internet_tips", "Internet quality and speed tips"),
                ],
                max_length=24,
            ),
        ),
    ]
