# Generated by Django 6.0.6 on 2026-06-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VPNProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("pasarguard", "PasarGuard"),
                            ("marzban", "Marzban"),
                            ("hiddify", "Hiddify"),
                            ("xui", "X-UI"),
                            ("connectix", "Connectix"),
                            ("custom", "Custom Provider"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("base_url", models.URLField()),
                ("api_key", models.CharField(max_length=500)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("max_users", models.PositiveIntegerField(default=1000)),
                ("current_users", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("health_status", models.CharField(default="unknown", max_length=20)),
                ("response_time", models.PositiveIntegerField(blank=True, null=True)),
                ("total_subscriptions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_providers",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "vpn_providers",
            },
        ),
        migrations.CreateModel(
            name="VPNProviderHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_time", models.DateTimeField()),
                ("is_healthy", models.BooleanField()),
                ("response_time", models.PositiveIntegerField()),
                ("api_accessible", models.BooleanField(default=False)),
                ("backend_running", models.BooleanField(default=False)),
                ("database_accessible", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                ("uptime", models.DurationField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="vpn_providers.vpnprovider",
                    ),
                ),
            ],
            options={
                "db_table": "vpn_provider_health_checks",
                "ordering": ["-check_time"],
            },
        ),
        migrations.CreateModel(
            name="VPNProviderInbound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("vmess", "VMess"),
                            ("vless", "VLESS"),
                            ("trojan", "Trojan"),
                            ("shadowsocks", "Shadowsocks"),
                            ("wireguard", "WireGuard"),
                            ("hysteria", "Hysteria"),
                        ],
                        max_length=20,
                    ),
                ),
                ("port", models.PositiveIntegerField()),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("stream_settings", models.JSONField(blank=True, default=dict)),
                ("max_users", models.PositiveIntegerField(default=100)),
                ("current_users", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbounds",
                        to="vpn_providers.vpnprovider",
                    ),
                ),
            ],
            options={
                "db_table": "vpn_provider_inbounds",
            },
        ),
        migrations.CreateModel(
            name="VPNProviderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create_user", "Create User"),
                            ("update_user", "Update User"),
                            ("delete_user", "Delete User"),
                            ("start_backend", "Start Backend"),
                            ("stop_backend", "Stop Backend"),
                            ("health_check", "Health Check"),
                            ("sync_users", "Sync Users"),
                            ("get_stats", "Get Statistics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("user_email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="vpn_providers.vpnprovider",
                    ),
                ),
            ],
            options={
                "db_table": "vpn_provider_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VPNProviderStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collected_at", models.DateTimeField()),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("online_users", models.PositiveIntegerField(default=0)),
                ("total_upload", models.BigIntegerField(default=0)),
                ("total_download", models.BigIntegerField(default=0)),
                (
                    "cpu_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "memory_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "disk_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("network_upload_speed", models.BigIntegerField(default=0)),
                ("network_download_speed", models.BigIntegerField(default=0)),
                ("additional_metrics", models.JSONField(blank=True, default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="vpn_providers.vpnprovider",
                    ),
                ),
            ],
            options={
                "db_table": "vpn_provider_stats",
                "ordering": ["-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="VPNServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=2)),
                ("ip_address", models.GenericIPAddressField()),
                ("port", models.PositiveIntegerField(default=443)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("max_users", models.PositiveIntegerField(default=100)),
                ("current_users", models.PositiveIntegerField(default=0)),
                (
                    "cpu_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "memory_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("bandwidth_usage", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                            ("overloaded", "Overloaded"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("inbound_configs", models.JSONField(blank=True, default=list)),
                ("protocols", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servers",
                        to="vpn_providers.vpnprovider",
                    ),
                ),
            ],
            options={
                "db_table": "vpn_servers",
            },
        ),
        migrations.AddIndex(
            model_name="vpnprovider",
            index=models.Index(
                fields=["brand", "status"], name="vpn_provide_brand_i_d0f70a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnprovider",
            index=models.Index(
                fields=["provider_type"], name="vpn_provide_provide_e575d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnprovider",
            index=models.Index(
                fields=["priority"], name="vpn_provide_priorit_ff1eab_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vpnprovider",
            unique_together={("brand", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="vpnproviderinbound",
            unique_together={("provider", "tag")},
        ),
        migrations.AddIndex(
            model_name="vpnproviderlog",
            index=models.Index(
                fields=["provider", "created_at"], name="vpn_provide_provide_5554c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnproviderlog",
            index=models.Index(
                fields=["level", "created_at"], name="vpn_provide_level_45d746_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnproviderlog",
            index=models.Index(
                fields=["action_type"], name="vpn_provide_action__142918_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vpnproviderstats",
            unique_together={("provider", "collected_at")},
        ),
        migrations.AlterUniqueTogether(
            name="vpnserver",
            unique_together={("provider", "name")},
        ),
    ]
