# Generated by Django 6.0.6 on 2026-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpn_providers", "0002_hiddify_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hiddifyadmin",
            new_name="hiddify_adm_provide_6efd41_idx",
            old_name="hiddify_admin_provider_mode_idx",
        ),
        migrations.RenameIndex(
            model_name="hiddifyadmin",
            new_name="hiddify_adm_telegra_530df0_idx",
            old_name="hiddify_admin_telegram_idx",
        ),
        migrations.AddField(
            model_name="vpnprovider",
            name="public_api_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
