# Generated by Django 6.0.6 on 2026-09-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vpn_providers",
            "0003_rename_hiddify_admin_provider_mode_idx_hiddify_adm_provide_6efd41_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vpnprovider",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
