# Generated by Django 6.0.6 on 2026-09-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn_providers", "0004_vpnprovider_last_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnprovider",
            name="api_key",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
