# Generated by Django 6.0.6 on 2026-06-07 08:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("user_registered", "User Registered"),
                            ("first_purchase", "First Purchase"),
                            ("subscription_expiring", "Subscription Expiring"),
                            ("subscription_expired", "Subscription Expired"),
                            ("inactivity", "User Inactivity"),
                            ("referral_milestone", "Referral Milestone"),
                            ("purchase_milestone", "Purchase Milestone"),
                            ("birthday", "User Birthday"),
                        ],
                        max_length=30,
                    ),
                ),
                ("trigger_conditions", models.JSONField(blank=True, default=dict)),
                ("delay_minutes", models.PositiveIntegerField(default=0)),
                ("max_sends_per_user", models.PositiveIntegerField(default=1)),
                ("cooldown_days", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("total_triggered", models.PositiveIntegerField(default=0)),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "automation_rules",
            },
        ),
        migrations.CreateModel(
            name="BroadcastCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing Campaign"),
                            ("announcement", "Announcement"),
                            ("notification", "Notification"),
                            ("survey", "Survey"),
                            ("promotional", "Promotional"),
                            ("emergency", "Emergency Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="broadcasts/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="broadcasts/videos/"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="broadcasts/documents/"
                    ),
                ),
                ("targeting_rules", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_ab_test", models.BooleanField(default=False)),
                ("ab_test_percentage", models.PositiveIntegerField(default=50)),
                ("send_immediately", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("retry_delay_minutes", models.PositiveIntegerField(default=5)),
                ("target_audience_count", models.PositiveIntegerField(default=0)),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                ("messages_delivered", models.PositiveIntegerField(default=0)),
                ("messages_failed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_campaigns",
                        to="brands.brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                ("messages_delivered", models.PositiveIntegerField(default=0)),
                ("messages_failed", models.PositiveIntegerField(default=0)),
                ("messages_read", models.PositiveIntegerField(default=0)),
                ("messages_clicked", models.PositiveIntegerField(default=0)),
                ("variant_a_sent", models.PositiveIntegerField(default=0)),
                ("variant_b_sent", models.PositiveIntegerField(default=0)),
                (
                    "variant_a_engagement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "variant_b_engagement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("conversions", models.PositiveIntegerField(default=0)),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="broadcasts.broadcastcampaign",
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Variant A"), ("B", "Variant B")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("platform", models.CharField(default="telegram", max_length=20)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                ("telegram_chat_id", models.BigIntegerField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("clicked", models.BooleanField(default=False)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="broadcasts.broadcastcampaign",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_messages",
            },
        ),
        migrations.CreateModel(
            name="AutomationExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("trigger_data", models.JSONField(blank=True, default=dict)),
                ("triggered_at", models.DateTimeField()),
                ("scheduled_for", models.DateTimeField()),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="broadcasts.automationrule",
                    ),
                ),
                (
                    "broadcast_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="broadcasts.broadcastmessage",
                    ),
                ),
            ],
            options={
                "db_table": "automation_executions",
            },
        ),
        migrations.CreateModel(
            name="BroadcastTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Message"),
                            ("promotion", "Promotional Message"),
                            ("reminder", "Reminder Message"),
                            ("expiry_warning", "Expiry Warning"),
                            ("renewal_offer", "Renewal Offer"),
                            ("custom", "Custom Template"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "subject_template",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("message_template", models.TextField()),
                ("available_variables", models.JSONField(blank=True, default=list)),
                (
                    "default_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="broadcast_templates/"
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_templates",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_templates",
            },
        ),
        migrations.AddField(
            model_name="automationrule",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_rules",
                to="broadcasts.broadcasttemplate",
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing Messages"),
                            ("announcements", "Announcements"),
                            ("reminders", "Reminders"),
                            ("expiry_alerts", "Expiry Alerts"),
                            ("promotional", "Promotional Offers"),
                            ("surveys", "Surveys"),
                            ("support", "Support Messages"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("telegram_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=False)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notification_preferences",
                        to="brands.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("icon", models.URLField(blank=True, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("action_url", models.URLField(blank=True, null=True)),
                ("action_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "device_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("platform", models.CharField(blank=True, max_length=20, null=True)),
                ("scheduled_for", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_notifications",
                        to="brands.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "push_notifications",
            },
        ),
        migrations.CreateModel(
            name="BroadcastAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("user_count", models.PositiveIntegerField(default=0)),
                ("last_calculated", models.DateTimeField(blank=True, null=True)),
                ("auto_update", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_audiences",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_audiences",
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="broadcastcampaign",
            index=models.Index(
                fields=["brand", "status"], name="broadcast_c_brand_i_6176ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastcampaign",
            index=models.Index(
                fields=["scheduled_at"], name="broadcast_c_schedul_d6e0e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastcampaign",
            index=models.Index(
                fields=["created_at"], name="broadcast_c_created_8ed506_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="broadcastanalytics",
            unique_together={("campaign", "date")},
        ),
        migrations.AddIndex(
            model_name="broadcastmessage",
            index=models.Index(
                fields=["campaign", "status"], name="broadcast_m_campaig_4d3a33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastmessage",
            index=models.Index(
                fields=["recipient", "status"], name="broadcast_m_recipie_46fccf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastmessage",
            index=models.Index(
                fields=["status", "queued_at"], name="broadcast_m_status_5bf1b0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="broadcastmessage",
            unique_together={("campaign", "recipient")},
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["rule", "status"], name="automation__rule_id_41f647_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["scheduled_for", "status"],
                name="automation__schedul_ff0169_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="broadcasttemplate",
            unique_together={("brand", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="automationrule",
            unique_together={("brand", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together={("user", "brand", "notification_type")},
        ),
        migrations.AddIndex(
            model_name="pushnotification",
            index=models.Index(
                fields=["user", "status"], name="push_notifi_user_id_d4b225_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotification",
            index=models.Index(
                fields=["scheduled_for", "status"],
                name="push_notifi_schedul_30c774_idx",
            ),
        ),
    ]
