# Generated by Django 6.0.6 on 2026-06-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("messages_received", models.PositiveIntegerField(default=0)),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                ("command_usage", models.JSONField(blank=True, default=dict)),
                ("popular_actions", models.JSONField(blank=True, default=dict)),
                ("errors_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_analytics",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "bot_analytics",
                "unique_together": {("brand", "date")},
            },
        ),
        migrations.CreateModel(
            name="BotCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("handler_function", models.CharField(max_length=255)),
                ("allowed_user_types", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_commands",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "bot_commands",
                "unique_together": {("brand", "command")},
            },
        ),
        migrations.CreateModel(
            name="BotKeyboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("keyboard_data", models.JSONField()),
                ("context", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_keyboards",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "bot_keyboards",
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_message_id", models.BigIntegerField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("inline_keyboard", "Inline Keyboard"),
                            ("poll", "Poll"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "handler_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=30, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_messages",
                        to="brands.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bot_messages",
                "indexes": [
                    models.Index(
                        fields=["user", "sent_at"],
                        name="bot_message_user_id_91054c_idx",
                    ),
                    models.Index(
                        fields=["brand", "sent_at"],
                        name="bot_message_brand_i_ccc206_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BotState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("main_menu", "Main Menu"),
                            ("profile_setup", "Profile Setup"),
                            ("purchase_flow", "Purchase Flow"),
                            ("payment_process", "Payment Process"),
                            ("support_ticket", "Support Ticket"),
                            ("referral_setup", "Referral Setup"),
                            ("subscription_management", "Subscription Management"),
                        ],
                        default="main_menu",
                        max_length=30,
                    ),
                ),
                ("state_data", models.JSONField(blank=True, default=dict)),
                ("last_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "last_inline_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_states",
                        to="brands.brand",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bot_states",
                "unique_together": {("user", "brand")},
            },
        ),
    ]
