# Generated by Django 6.0.6 on 2026-06-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_alter_botstate_current_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botstate",
            name="current_state",
            field=models.CharField(
                choices=[
                    ("main_menu", "Main Menu"),
                    ("profile_setup", "Profile Setup"),
                    ("profile_edit", "Profile Edit"),
                    ("purchase_flow", "Purchase Flow"),
                    ("payment_process", "Payment Process"),
                    ("support_ticket", "Support Ticket"),
                    ("referral_setup", "Referral Setup"),
                    ("subscription_management", "Subscription Management"),
                    ("admin_action", "Admin Action"),
                ],
                default="main_menu",
                max_length=30,
            ),
        ),
    ]
