# Generated by Django 6.0.6 on 2026-10-09 17:55

from django.db import migrations, models


def preserve_existing_welcome(apps, schema_editor):
    states = apps.get_model("bot", "BotState")
    states.objects.using(schema_editor.connection.alias).update(
        welcome_shown_at=models.F("created_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_botstate_current_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="botstate",
            name="welcome_shown_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_existing_welcome, migrations.RunPython.noop),
    ]
